### ISSUE TITLE
Mysql issue 

### ISSUE THREAD

**Issue by aelharda** [IamCarron/DVWA-Script#1]
I saw two errors with the install:
1-Perl-base dependencies are older
2- keeps asking about sql user and pwd in a loop. Please reference the video below:

https://github.com/IamCarron/DVWA-Script/assets/49875883/c209699b-2f4e-496d-82b0-708f393dc921

**Comment by IamCarron** [comment]
Hi! You need to run the script with the root user in order to use the blank password.

Referring for the older dependencies those packages are the ones that you already have on your SO so you need to a "sudo apt upgrade" first. Then it shouldn't bee any problem on using the installer.

Also If you can send me the result of this command ${LANG:0:2} in order to check the system language I so some Spanish and the rest English on some messages.

**Comment by aelharda** [comment]
```
Welcome to Linux Lite 6.6 
Support - https://www.linuxliteos.com/forums/ (Right click, Open Link)
 
 anasrocks  ~  ${LANG:0:2}
en: command not found
```
also my perl-base version is higher than the required one

`apt list perl-base
Listing... Done
perl-base/now 5.36.0-10+b1 amd64 [installed,local]
perl-base/jammy-updates,jammy-security 5.34.0-3ubuntu1.3 i386`
